### ISSUE TITLE
新型更新システムの提案

### ISSUE THREAD

**Issue by sousuke0422** [yupix/amb#7]
- 手元とリモートを同期
- 新しいタグがあるかを確認
- もしあるならそこにcheckout
  - なければ放置

これらはgitコマンドを主体として実装化

**Comment by yupix** [comment]
今の所、実装する予定はないです、
代わりに、[4eb93ff](https://github.com/yupix/amb/commit/4eb93fffa2d34071226d045ad78734b31bb3d4b4)
のコミットにて、修正及び、仕様の変更を行いました
