### ISSUE TITLE
setsettings等のコマンドでの既存のバグ

### ISSUE THREAD

**Issue by yupix** [yupix/amb#9]
setSettingsなどでは、主にsettings.txt等の変数を変更し、
それにあった動作を可能としていますが、現在の仕様だと、これはある意味
このProject一番のバグ要因となることでしょう、先程も申したとおり、
現在のsetSettingsコマンドではyes or no を打つことにより、yesならその動作をといった物です。そして、setSettingsは**yes or no以外を打つことも可能です** つまり、現在の仕様を変更しない限り、誤って、ye等でEnterを押してしまった場合等、ほぼ確実にその設定は手動でsettingsを変更するまでは、壊れることは間違いありません、 これは非常に良くないことです。
このバグ要因となりうる物の修正を現段階での、最優先事項とします。

**Comment by sousuke0422** [comment]
1でyes、2でnoが一般的で簡単なはずです

**Comment by yupix** [comment]
このバグは[cf8009a](https://github.com/yupix/amb/commit/cf8009a7cba96182d2fa5c70793613b64f5f7314)対策が施されました。 sousuke氏の案に関しては今後の作成物の参考にさせていただきます。
今回は最初に (Y)es (N)oといった具合に y or n形式でやることにしました。
